/**
 * 메가커피 메뉴 데이터
 * 전체 메뉴 리스트를 카테고리별로 분류하여 저장
 * 
 * 각 메뉴 객체 구조:
 * - name: 메뉴 이름
 * - category: 카테고리 (커피, 티, 에이드&주스, 스무디&프라페, 디카페인, 음료, 신상품)
 */

const MENU_DATA = [
    // 커피
    { name: "그린티크림라떼", category: "커피" },
    { name: "꿀아메리카노", category: "커피" },
    { name: "달달연유라떼", category: "커피" },
    { name: "더블엑소아메리카노", category: "커피" },
    { name: "더블엑소카페라떼", category: "커피" },
    { name: "돌체라떼", category: "커피" },
    { name: "로얄밀크티라떼", category: "커피" },
    { name: "마끼아또", category: "커피" },
    { name: "메가라떼", category: "커피" },
    { name: "메가리카노", category: "커피" },
    { name: "바닐라라떼", category: "커피" },
    { name: "블랙펄카페라떼", category: "커피" },
    { name: "브라우니라떼", category: "커피" },
    { name: "블루베리요거트라떼", category: "커피" },
    { name: "솔티드카라멜라떼", category: "커피" },
    { name: "아메리카노", category: "커피" },
    { name: "아이스크림라떼", category: "커피" },
    { name: "에스프레소", category: "커피" },
    { name: "연유라떼", category: "커피" },
    { name: "오레오크림라떼", category: "커피" },
    { name: "카라멜마끼아또", category: "커피" },
    { name: "카페모카", category: "커피" },
    { name: "카페라떼", category: "커피" },
    { name: "카푸치노", category: "커피" },
    { name: "콜드브루", category: "커피" },
    { name: "콜드브루라떼", category: "커피" },
    { name: "쿠키앤크림라떼", category: "커피" },
    { name: "크림카페라떼", category: "커피" },
    { name: "헤이즐넛라떼", category: "커피" },
    { name: "허니크림라떼", category: "커피" },

    // 티
    { name: "고구마라떼", category: "티" },
    { name: "그린티라떼", category: "티" },
    { name: "녹차라떼", category: "티" },
    { name: "대추차", category: "티" },
    { name: "딸기라떼", category: "티" },
    { name: "레몬티", category: "티" },
    { name: "민트초코라떼", category: "티" },
    { name: "밀크티", category: "티" },
    { name: "복숭아아이스티", category: "티" },
    { name: "블랙밀크티", category: "티" },
    { name: "생강차", category: "티" },
    { name: "쌍화차", category: "티" },
    { name: "얼그레이", category: "티" },
    { name: "유자차", category: "티" },
    { name: "자몽티", category: "티" },
    { name: "재스민티", category: "티" },
    { name: "초코라떼", category: "티" },
    { name: "캐모마일", category: "티" },
    { name: "타로밀크티", category: "티" },
    { name: "페퍼민트", category: "티" },
    { name: "흑당밀크티", category: "티" },
    { name: "흑임자라떼", category: "티" },

    // 에이드&주스
    { name: "경상애플주스", category: "에이드&주스" },
    { name: "그린애플에이드", category: "에이드&주스" },
    { name: "딸기에이드", category: "에이드&주스" },
    { name: "레몬에이드", category: "에이드&주스" },
    { name: "레몬크러쉬", category: "에이드&주스" },
    { name: "망고주스", category: "에이드&주스" },
    { name: "망고패션후르츠에이드", category: "에이드&주스" },
    { name: "모히또", category: "에이드&주스" },
    { name: "복숭아에이드", category: "에이드&주스" },
    { name: "블루레모네이드", category: "에이드&주스" },
    { name: "블루베리에이드", category: "에이드&주스" },
    { name: "블루베리주스", category: "에이드&주스" },
    { name: "사과주스", category: "에이드&주스" },
    { name: "석류에이드", category: "에이드&주스" },
    { name: "수박주스", category: "에이드&주스" },
    { name: "오렌지주스", category: "에이드&주스" },
    { name: "자몽에이드", category: "에이드&주스" },
    { name: "청포도에이드", category: "에이드&주스" },
    { name: "체리콕", category: "에이드&주스" },
    { name: "키위주스", category: "에이드&주스" },
    { name: "토마토주스", category: "에이드&주스" },
    { name: "패션후르츠에이드", category: "에이드&주스" },
    { name: "포도주스", category: "에이드&주스" },

    // 스무디&프라페
    { name: "그린티프라페", category: "스무디&프라페" },
    { name: "딸기스무디", category: "스무디&프라페" },
    { name: "딸기요거트스무디", category: "스무디&프라페" },
    { name: "딸기쿠키프라페", category: "스무디&프라페" },
    { name: "라즈베리프라페", category: "스무디&프라페" },
    { name: "망고스무디", category: "스무디&프라페" },
    { name: "망고요거트스무디", category: "스무디&프라페" },
    { name: "모카프라페", category: "스무디&프라페" },
    { name: "민트초코프라페", category: "스무디&프라페" },
    { name: "블루베리스무디", category: "스무디&프라페" },
    { name: "블루베리요거트스무디", category: "스무디&프라페" },
    { name: "샤인머스캣스무디", category: "스무디&프라페" },
    { name: "쿠키프라페", category: "스무디&프라페" },
    { name: "초코칩프라페", category: "스무디&프라페" },
    { name: "초코프라페", category: "스무디&프라페" },
    { name: "커피프라페", category: "스무디&프라페" },
    { name: "캐라멜프라페", category: "스무디&프라페" },
    { name: "쿨라임모히또", category: "스무디&프라페" },
    { name: "플레인요거트스무디", category: "스무디&프라페" },

    // 디카페인
    { name: "디카페인 아메리카노", category: "디카페인" },
    { name: "디카페인 카페라떼", category: "디카페인" },
    { name: "디카페인 카라멜마끼아또", category: "디카페인" },
    { name: "디카페인 바닐라라떼", category: "디카페인" },
    { name: "디카페인 헤이즐넛라떼", category: "디카페인" },
    { name: "디카페인 카페모카", category: "디카페인" },
    { name: "디카페인 돌체라떼", category: "디카페인" },

    // 음료
    { name: "메가에이드", category: "음료" },
    { name: "메가콜라", category: "음료" },
    { name: "메가사이다", category: "음료" },
    { name: "미숫가루", category: "음료" },
    { name: "바나나우유", category: "음료" },
    { name: "딸기우유", category: "음료" },
    { name: "초코우유", category: "음료" },
    { name: "우유", category: "음료" },
    { name: "탄산수", category: "음료" },
    { name: "생수", category: "음료" },

    // 신상품
    { name: "딸기젤라또", category: "신상품" },
    { name: "딸기말차젤라또", category: "신상품" },
    { name: "딸기초코라떼", category: "신상품" },
    { name: "딸기프라페", category: "신상품" },
    { name: "딸기젤리워터", category: "신상품" },
    { name: "엠쥐씨가꾼딸기꿈", category: "신상품" },
    { name: "복숭아바질티", category: "신상품" },
    { name: "자몽바질티", category: "신상품" },
    { name: "청포도바질티", category: "신상품" },
    { name: "흑당버블라떼", category: "신상품" },
    { name: "흑당버블밀크티", category: "신상품" },
    { name: "메가시그니처라떼", category: "신상품" },
    { name: "메가토피넛라떼", category: "신상품" },
    { name: "제주말차라떼", category: "신상품" },
    { name: "제주녹차라떼", category: "신상품" },
    { name: "크림치즈라떼", category: "신상품" },
    { name: "누텔라라떼", category: "신상품" },
    { name: "비엔나커피", category: "신상품" },
    { name: "아인슈페너", category: "신상품" },
    { name: "코코넛커피", category: "신상품" },
    { name: "더블샷라떼", category: "신상품" },
    { name: "콜드브루크림라떼", category: "신상품" },
    { name: "메가CCL", category: "신상품" },
    { name: "흑당크림라떼", category: "신상품" },
    { name: "생크림라떼", category: "신상품" },
];

/**
 * 전체 카테고리 목록
 */
const CATEGORIES = [
    "전체",
    "커피",
    "티",
    "에이드&주스",
    "스무디&프라페",
    "디카페인",
    "음료",
    "신상품"
];
